### ISSUE TITLE
version without worker

### ISSUE THREAD

**Issue by v11580** [op12no2/lozza#3]
Is there somewhere I can find a working example of lozza that executes without a web worker?

Thank you in advance and congratulations to the developers for the outstanding chess engine.

**Comment by op12no2** [comment]
Hi, not a complete working version no. The problem is that without workers you cannot update the page while Lozza is working. However there are partial examples in texeltune*.js where I set up a FEN and call eval and/or Q search on it. From that it should be clear what is involved. Thanks for your kind words :)

**Comment by v11580** [comment]
Thanks for writing. I installed npm, so I was able to get up and running. Yours is one of the few JS engines (the only one I actually know of) that returns the move in descriptive notation. Plus it's not so bad in the elo department either. Chess is a double hobby for me: coding JS and learning the game (class B player.) Cheers from the USA. I was in Wales briefly about 20 years ago while visiting the UK for tow weeks.  Gary
